- src/script.js
Noticed bundling was all messed up. Did a bit of debugging. It looks like "Starred" was being detected by looking at the title attribute. That doesn't seem to be getting set anymore so it was assuming everything was Starred... Might be better to have a default that isn't true, but I changed it to use the ariaLabel and the bundling seems to be working again.
Apparently my IDE also stripped a bunch of unnecessary whitespace.
> fix(bundling): Updating to use ariaLabel instead of Title. Resolves #9

- manifest.json
Bumping version due to merged changes from https://github.com/team-inbox/inbox-reborn/pull/17#issue-571471907
..and also since FF add-on dev portal yelled at me when uploading + signing this new version with the old version intact
> bump version to finalize PR#17

- manifest.json
- src/script.js
Something changed in the HTML that broke the retrieval of the user's email address. Hopefully this fix is more robust
> Fix reminders (again)

- manifest.json
- src/script.js
- src/style.css
Fixes #20 
Sry bout the wait for all you early adopters trynna keep those Inbox memories alive 🙃
> New Chat layout patch

- src/script.js
Fixed issue: https://github.com/team-inbox/inbox-reborn/issues/29
> Fix the compose button

- src/script.js
The previous fix broke things for people still on the old layout. I think this PR addresses that (hard to test as I don't have new layout anywhere)
> Fixes compose button to work with old and new variations

- manifest.json
- src/script.js
- src/style.css
Some small stuff had changed that was breaking the title and colour changing in the header. This should hopefully address that. Also fixes the compose button again that got broken by the same GMail changes
Bonus fix: Changed title for 'Settings' page to 'Inbox' that was previously showing 'Search' - didn't use 'Settings' as there is already a 'Settings' heading
> Fix Header & Compose Button Issues

- manifest.json
- src/script.js
Noticed this got b0rked with a recent update.. and apparently I had already set myself up to patch with minimal effort 😅
Thankfully, issue only affected UI after opening the Calendar/Keep/Tasks/Contacts sidebar.
> Add hotfix for floating compose button positioning with open app sidebar

- src/script.js
Fixed a couple of problems:
- Compose button did not appear
- Uncaught TypeError: Cannot read properties of null (reading 'classList') [script.js:882]
Tested working on Chrome 98.0.4758.80
Other detected errors that need to be fixed:
- Email address not retrieved correctly by getMyEmailAddress
> Fixed Compose button and Uncaught TypeError

- manifest.json
- src/script.js
The previous update resulted in the compose button never appearing. This fixes that issue
> Fixes "Floating Compose" regression + more

- src/script.js
This fixes the problem of the floating button not being moved when the sidebar is initially fully closed before use, and is only used after clicking the open button (bottom right)
> Fix small further small issue with sidebar

- manifest.json
- src/script.js
I noticed that the Reminders feature was no longer working due to the email retrieval being busted. This PR fixes the issue
> Fix Reminders Feature

- manifest.json
- src/script.js
This was broken for some time. Got round to fixing it a few months back, but been too busy to do the PR.
> Fixes "only bundle if more than one" feature

- manifest.json
- src/script.js
- src/style.css
By no surprise, Google made breaking changes affecting the extension.
..you'll want to update README with new version number / chrome link after merging and rolling out to chrome web store
> Fixes side panel + floating button functionality + email bundling

- manifest.json
- src/script.js
Google changed the email address CSS selectors.. again.
> Bundling fix

- manifest.json
- src/script.js
Google has updated CSS classes used on element used for grabbing email address, once again.
> (Another) bundling fix

- manifest.json
- src/script.js
Seems like it was easier to fix than I first thought
> Fixes (hopefully) create reminder functionality

- README.md
- manifest.json
- src/script.js
Should work for both US and UK locales now
> Small change to Sidebar CSS Selector

- src/script.js
Gmail seems to have changed the class names where select.emails get emails from. This updates the class names queried so bundles work again
> Update select.emails querySelectorAll

- manifest.json
- src/script.js
- src/style.css
Mostly just updating a few selectors to alleviate some wonkiness introduced in my last PR 😓
Also a minor style tweak to Quick Settings panel.
> Better bundling + inline label hiding "fixed" in last PR

- manifest.json
Can you check if this fixes the issue in https://github.com/team-inbox/inbox-reborn/issues/85 ?
> fix: apply extension only to mail page UI

- chrome.json
- firefox.json
- src/style.css
-Fixed issue
-Cleaned up more of the dark theme to mimmic Gmail dark theme 
-Updated to version 2.0.2 tested on both Firefox and Chrome looks amazing!
> Issue #103
